name: .NET Core
on:
  push:
    branches: 
    - dev
    - featureDev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
           dotnet-version: '7.0.x'
           source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Install dependencies
        run: dotnet restore CoreLibraries/OnEntitySharedLogic/OnEntitySharedLogic.csproj
  
      - name: Build
        run: dotnet build --configuration Release --no-restore CoreLibraries/OnEntitySharedLogic/OnEntitySharedLogic.csproj
  
      - name: Test
        run: dotnet test --no-restore --verbosity normal CoreLibraries/OnEntitySharedLogic/OnEntitySharedLogic.csproj
  
      - name: Pack
        run: dotnet pack --no-build --configuration Release CoreLibraries/OnEntitySharedLogic/OnEntitySharedLogic.csproj --output .
  
      - name: Push to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --no-symbols --skip-duplicate
