name: .NET Core
on:
  push:
    branches: 
    - dev
    - featureDev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          
      - name: Install dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  
      - name: Pack
        run: dotnet pack --no-build --configuration Release Internship-University-Scheduler-Api/OnEntitySharedLogic.csproj --output .
  
      - name: Push to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }} 
        run: dotnet nuget push *.nupkg --api-key ${{ env.NUGET_AUTH_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --no-symbols --skip-duplicate
