name: .NET Core
on:
  push:
    branches: 
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'  # Specifies to use the latest patch version of .NET 6
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GHUB_TOKEN}}
          
      - name: Install dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  
      - name: Pack
        run: dotnet pack --no-build --configuration Release SharedLogicLibrary/SharedLogicLibrary.csproj --output .
  
      # - name: Push to NuGet.org
      #   run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_PACKAGE_SECRET }} --skip-duplicate
  
      - name: Push to GitHub Packages
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GHUB_TOKEN }}  --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --no-symbols --skip-duplicate
